// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIlBGfMzaw2B8okV0X-MtLg0U22A5wSco',
    appId: '1:71143989812:web:772cc4d71a7b529af7e061',
    messagingSenderId: '71143989812',
    projectId: 'jobquest-3dbb3',
    authDomain: 'jobquest-3dbb3.firebaseapp.com',
    storageBucket: 'jobquest-3dbb3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM2NMZ1bjqS_wCCwu3K9AwXDUNQ_qDLl0',
    appId: '1:71143989812:android:c07a9eb1c462db9bf7e061',
    messagingSenderId: '71143989812',
    projectId: 'jobquest-3dbb3',
    storageBucket: 'jobquest-3dbb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPKi1vjgH5ZgR91l_n2IYOj-NGZ4muhNI',
    appId: '1:71143989812:ios:70462f28d8d9ee84f7e061',
    messagingSenderId: '71143989812',
    projectId: 'jobquest-3dbb3',
    storageBucket: 'jobquest-3dbb3.appspot.com',
    iosBundleId: 'com.example.jobQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPKi1vjgH5ZgR91l_n2IYOj-NGZ4muhNI',
    appId: '1:71143989812:ios:70462f28d8d9ee84f7e061',
    messagingSenderId: '71143989812',
    projectId: 'jobquest-3dbb3',
    storageBucket: 'jobquest-3dbb3.appspot.com',
    iosBundleId: 'com.example.jobQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIlBGfMzaw2B8okV0X-MtLg0U22A5wSco',
    appId: '1:71143989812:web:18aa655d15d73af4f7e061',
    messagingSenderId: '71143989812',
    projectId: 'jobquest-3dbb3',
    authDomain: 'jobquest-3dbb3.firebaseapp.com',
    storageBucket: 'jobquest-3dbb3.appspot.com',
  );
}
